name: Build and deploy Node.js app to Azure Web App - maneeshwebapp

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v3
        with:
          node-version: '20.x'

      - run: npm ci

      - run: npm run build

      - uses: actions/upload-artifact@v4
        with:
          name: react-build
          path: build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: react-build
          path: .

      - uses: azure/webapps-deploy@v3
        with:
          app-name: 'maneeshwebapp'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_B52254F6B063428BB830F5ED40188C73 }}
          package: .
