name: Build and deploy React app to Azure Web App - candidatewebapp

on:
  push:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    defaults:
      run:
        working-directory: ./web-app

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build React app
        env:
          REACT_APP_FUNCTION_URL: https://candidatefuncapp.azurewebsites.net
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: react-app
          path: web-app/build

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: react-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: candidatewebapp
          slot-name: Production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_64AEF982D9824430A854575777E9D8A5 }}
          package: .
